{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"When the credentials renewal fails because the user was deleted.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"metadata":{"externalID":"s:5Auth019AuthenticationErrorV21isRefreshTokenDeletedSbvp","symbolKind":"property","roleHeading":"Instance Property","title":"isRefreshTokenDeleted","role":"symbol","modules":[{"name":"Auth0"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/isRefreshTokenDeleted":{"title":"isRefreshTokenDeleted","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","url":"\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted","abstract":[{"text":"When the credentials renewal fails because the user was deleted.","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","title":"AuthenticationError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"url":"\/documentation\/auth0\/authenticationerror","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}]}}}