{"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRefreshTokenDeleted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"Auth0"}],"roleHeading":"Instance Property","title":"isRefreshTokenDeleted","externalID":"s:5Auth019AuthenticationErrorV21isRefreshTokenDeletedSbvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"abstract":[{"text":"When the credentials renewal fails because the user was deleted.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted"]}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.auth0.Auth0/documentation/Auth0":{"title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/isRefreshTokenDeleted":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","abstract":[{"type":"text","text":"When the credentials renewal fails because the user was deleted."}],"kind":"symbol","type":"topic","role":"symbol","title":"isRefreshTokenDeleted","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"url":"\/documentation\/auth0\/authenticationerror","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"title":"AuthenticationError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}]}}}