{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"metadata":{"modules":[{"name":"Auth0"}],"roleHeading":"API Collection","title":"LocalizedError Implementations","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"title":"failureReason","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/failurereason"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"title":"helpAnchor","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/helpanchor"},"doc://com.auth0.Auth0/documentation/Auth0":{"kind":"symbol","url":"\/documentation\/auth0","role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"type":"topic","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"kind":"symbol","url":"\/documentation\/auth0\/authenticationerror","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","role":"symbol","title":"AuthenticationError","abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"title":"recoverySuggestion","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion"}}}