{"metadata":{"role":"collectionGroup","modules":[{"name":"Auth0"}],"title":"Auth0Error Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations"},"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"kind":"article","topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","title":"Auth0","url":"\/documentation\/auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","role":"collection","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","type":"topic","abstract":[{"text":"Description of the error.","type":"text"}],"title":"localizedDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"title":"CredentialsManagerError","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"abstract":[{"text":"Description of the error.","type":"text"}],"title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","role":"symbol","kind":"symbol","type":"topic"}}}