{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"Auth0"}],"title":"Auth0Error Implementations"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"kind":"article","references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"errorDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","abstract":[{"text":"Description of the error.","type":"text"}],"role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"kind":"symbol","title":"localizedDescription","abstract":[{"type":"text","text":"Description of the error."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","role":"symbol","type":"topic"},"doc://com.auth0.Auth0/documentation/Auth0":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"title":"Auth0","role":"collection","type":"topic","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"title":"CredentialsManagerError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}]}}}