{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Auth0Error Implementations","modules":[{"name":"Auth0"}]},"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"article","sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","title":"errorDescription","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Description of the error."}],"url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"role":"symbol","type":"topic","title":"localizedDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","abstract":[{"type":"text","text":"Description of the error."}],"kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","url":"\/documentation\/auth0","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"title":"CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror","type":"topic","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"kind":"symbol"}}}