{"sections":[],"metadata":{"title":"Auth0Error Implementations","role":"collectionGroup","modules":[{"name":"Auth0"}],"roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"title":"errorDescription","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","role":"symbol","abstract":[{"type":"text","text":"Description of the error."}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"type":"topic","title":"localizedDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Description of the error."}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","role":"symbol","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","role":"collection","title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","kind":"symbol","abstract":[{"text":"SDK for Apple platforms.","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"title":"CredentialsManagerError","url":"\/documentation\/auth0\/credentialsmanagererror","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CredentialsManagerError"}],"navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}]}}}