{"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"kind":"article","metadata":{"title":"Auth0Error Implementations","modules":[{"name":"Auth0"}],"roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","role":"collection","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"type":"topic","kind":"symbol","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Description of the error.","type":"text"}],"title":"localizedDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","role":"symbol","kind":"symbol","title":"errorDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","type":"topic","abstract":[{"type":"text","text":"Description of the error."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","title":"CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}]}}}