{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"kind":"article","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"Auth0Error Implementations","modules":[{"name":"Auth0"}],"role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations"},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","kind":"symbol","title":"errorDescription","type":"topic","abstract":[{"type":"text","text":"Description of the error."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"url":"\/documentation\/auth0\/credentialsmanagererror","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","title":"CredentialsManagerError","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","title":"localizedDescription","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Description of the error.","type":"text"}],"kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription"}}}