{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Auth0Error Implementations","modules":[{"name":"Auth0"}]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"abstract":[{"type":"text","text":"Description of the error."}],"title":"errorDescription","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","type":"topic","abstract":[{"type":"text","text":"Description of the error."}],"title":"localizedDescription","role":"symbol","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"title":"CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"url":"\/documentation\/auth0\/credentialsmanagererror","type":"topic","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","type":"topic","title":"Auth0","url":"\/documentation\/auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","abstract":[{"text":"SDK for Apple platforms.","type":"text"}]}}}