{"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"Auth0"}],"role":"collectionGroup","title":"Auth0Error Implementations"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"generated":true}],"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"abstract":[{"type":"text","text":"Description of the error."}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","title":"errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}],"abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CredentialsManagerError"}],"type":"topic","title":"CredentialsManagerError","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror"},"doc://com.auth0.Auth0/documentation/Auth0":{"title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"abstract":[{"type":"text","text":"Description of the error."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"localizedDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","kind":"symbol"}}}