{"sections":[],"kind":"article","metadata":{"modules":[{"name":"Auth0"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Auth0Error Implementations"},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"anchor":"Instance-Properties","title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"abstract":[{"type":"text","text":"Description of the error."}],"title":"localizedDescription","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"url":"\/documentation\/auth0\/credentialsmanagererror","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"title":"CredentialsManagerError","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}]},"doc://com.auth0.Auth0/documentation/Auth0":{"kind":"symbol","url":"\/documentation\/auth0","role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"type":"topic","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"errorDescription","type":"topic","abstract":[{"type":"text","text":"Description of the error."}],"kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription"}}}