{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"generated":true,"anchor":"Instance-Properties"}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Auth0"}],"role":"collectionGroup","title":"Auth0Error Implementations"},"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","type":"topic","role":"symbol","abstract":[{"text":"Description of the error.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"url":"\/documentation\/auth0\/credentialsmanagererror","type":"topic","kind":"symbol","title":"CredentialsManagerError"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","abstract":[{"text":"Description of the error.","type":"text"}],"title":"localizedDescription","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","url":"\/documentation\/auth0","kind":"symbol","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"type":"topic","title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0"}}}