{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noCredentials","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","text":"CredentialsManagerError","kind":"typeIdentifier","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","isActive":true},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"metadata":{"title":"noCredentials","externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ","modules":[{"name":"Auth0"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noCredentials","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CredentialsManagerError","kind":"typeIdentifier","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"title":"CredentialsManagerError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}]},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"abstract":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" value, if any. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","title":"cause","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cause","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/auth0\/auth0error\/cause-9wuyi","type":"topic"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","kind":"symbol","type":"topic","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"role":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError"}],"kind":"symbol","title":"noCredentials","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","isActive":true},{"type":"text","text":"."}]}}}