{"abstract":[{"text":"No credentials were found in the store.","type":"text"},{"type":"text","text":" "},{"text":"This error does not include a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","isActive":true},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"]}],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"noCredentials","kind":"identifier"},{"kind":"text","text":": "},{"text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","kind":"typeIdentifier"}],"role":"symbol","title":"noCredentials","modules":[{"name":"Auth0"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"noCredentials","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError","kind":"typeIdentifier"}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"title":"CredentialsManagerError","url":"\/documentation\/auth0\/credentialsmanagererror","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CredentialsManagerError"}],"navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError","kind":"typeIdentifier"}],"kind":"symbol","title":"noCredentials","type":"topic","role":"symbol","abstract":[{"text":"No credentials were found in the store.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},{"text":".","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","role":"collection","title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","kind":"symbol","abstract":[{"text":"SDK for Apple platforms.","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","title":"cause","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" value, if any. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"url":"\/documentation\/auth0\/auth0error\/cause-9wuyi","type":"topic"}}}